version: '3.9'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - "./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - application
  application:
    build:
      context: .
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - database
  database:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=scott
      - POSTGRES_PASSWORD=tiger
    ports:
      - "5432:5432"